### PR TITLE
Hack to handle g-zip when parsing WARC files

### PR DESCRIPTION
**Pull request by lljrsr**
Before this "patch" warctools used the Content-Length field to determine the length of the body. Since the g-zipped bodies are no longer g-zipped in WARC files, this resulted in an error.
This is not the nicest fix. I would appreciate any input in how to fix this properly.
A merge to master would be great :) .

### CODE REVIEW

**Comment by gojomo** [comment]
Hmm.... WARC record content-blocks should be the verbatim bytes as delivered by HTTP. So, gzipped bodies *should* still be gzipped in WARC files. 

If there are WARCs where this doesn't appear to be the case, that may indicate a bug in the WARC-writing that's best fixed there.

**Comment by lljrsr** [comment]
I have been using [a common-crawl WARC file](https://aws-publicdatasets.s3.amazonaws.com/common-crawl/crawl-data/CC-MAIN-2015-40/segments/1443738099622.98/warc/CC-MAIN-20151001222139-00240-ip-10-137-6-227.ec2.internal.warc.gz). When extracting with warcunpack_ia.py tool on master branch you will get a lot of "truncated http response" warnings because the Content-Length does not match the actual length in the WARC file.
Since this is an official common-crawl WARC file, I would not assume that there is a bug in the WARC-writing.
On my branch this issue does not appear any longer.

What do you think?

**Comment by nlevitt** [comment]
Yeah definitely looks like a bug in warc writing. Seems to be this warc writer: https://wiki.apache.org/nutch/CommonCrawlDataDumper

Warctools has some other hacks to handle broken arcs and warcs, so I wouldn't necessarily rule out merging this change. But first I think it's important the CommonCrawlDataDumper developers are aware of the problem and have a chance to weigh in. Maybe they'll say "it's just a few warcs, don't worry about it, we'll fix them". Who knows. @lljrsr want to file an issue with them and point to this discussion?

Also the unit tests need to be fixed before this can be merged.
https://travis-ci.org/internetarchive/warctools/builds/106808044
And it would be good to add a test for this feature, and another for correct `content-encoding: gzip` records, to make sure this change doesn't break those.

**Comment by lljrsr** [comment]
Alright. Thanks for the reply. I have opened up [an issue](https://issues.apache.org/jira/browse/NUTCH-2213).

**Comment by jnioche** [comment]
@nlevitt The code used to generate the CommonCrawl WARC files is [https://github.com/commoncrawl/nutch/blob/cc/src/java/org/commoncrawl/tools/WarcExport.java]. 

@lljrsr already reported the issue on the CommonCrawl user list, thanks for that. 

I'll have a look and see if I can find an explanation for it. I am the temporary crawl manager for CommonCrawl this month (until the person they hired starts working for them) so I am definitely up for fixing any issues with it if I can.

**Comment by jnioche** [comment]
Fixed in [https://github.com/commoncrawl/nutch/commit/3551eb6dbb7f7152a13d2e4eb0f8eb6014dc8252].

The crawler stored the response headers including the content length even though Nutch stores the content decompressed.  This will be used in the next release of CC, thanks for reporting it.

**Comment by lljrsr** [comment]
Nice! Now.. is there a big portion of WARC files which has this issue?

**Comment by jnioche** [comment]
No idea how frequent this is, your guess is as good as mine.

**Comment by tfmorris** [comment]
It looks to me like the use of verbatim headers was enabled in Nov. 2013

https://github.com/commoncrawl/nutch/commit/2acd111890aa6c23920d6dd1412a5d11deb63e9f

**Comment by lljrsr** [comment]
Good to know :) . Thanks!
Since it seems to be quite frequent I will try to think of some command line option which enables parsing those broken files.

**Comment by tfmorris** [comment]
@gojomo The [spec](http://bibnum.bnf.fr/WARC/WARC_ISO_28500_version1_latestdraft.pdf) says that the body should be stored _after removing the transfer-encoding_.

@lljrsr The draft of the spec that you pointed to is old. It may be pretty close, but better to use the latest available (sadly, the real ISO spec costs $$$, or CHF)

**Comment by lljrsr** [comment]
Alright. Thanks for clarifying :) .

**Comment by ikreymer** [comment]
A bit late to this but my thoughts in general:

Unfortunately, this is a case where ambiguity and different implementations have caused issues such as this. I was not aware of that 'transfer-encoding' statement, and I think some tools (warcprox) may not remove the transfer-encoding. However, transfer-encoding (eg. chunked) is different from the content-encoding (eg. gzip, deflate). Removing the gzip encoding does not seem to be the correct approach, as it unnecessarily increases storage size. It is quite unfortunate that Nutch stores the content decompressed. I believe the spirit of the WARC standard is to store the data as close as possible to the byte-by-byte transmission that was received, decompressing the record violates this, and invalidates the HTTP headers that are present.

Probably the only correct implementation for reading is something like following:

if transfer-encoding: chunked is present, assume chunked encoding but fallback gracefully to no encoding.

if content-encoding is present, attempt to decompress but fallback gracefully to no encoding.

The pywb tools attempt to follow this general approach, though probably should double-check this also.

**Comment by ikreymer** [comment]
This statement regarding transfer-encoding is being clarified in the next WARC standard revision.
Here is a link to @gojomo comment clarifying this even better:
https://github.com/iipc/warc-specifications/issues/22#issuecomment-126949173

**Comment by nlevitt** [comment]
@jnioche @tfmorris @ikreymer Thank you for your helpful input.

ikreymer commented a minute ago
> if content-encoding is present, attempt to decompress but fallback gracefully to no encoding.

+1. @lljrsr, ideally your pull request shouldn't add any command line options. If the `Content-encoding: gzip` header is present, warctools should detect if the payload is gzipped or not, and proceed accordingly.

**Comment by gojomo** [comment]
@tfmorris (& @ikreymer) – The WARC spec does *not* suggest the removal of the transfer encoding when storing HTTP responses. The relevant text is:

> For a target-URI of the 'http' or 'https' schemes, a 'response' record block should contain the full HTTP
> response received over the network, including headers. That is, it contains the 'Response' message
> defined by section 6 of HTTP/1.1 (RFC2616), or by any previous or subsequent version of HTTP
> compatible with the section 6 of HTTP/1.1 (RFC2616). 

There is no allowance for removing a transfer-encoding or mutating the 'Response' message (as one kind of 'HTTP-message') in any way. Any separate definitions of 'payload' elsewhere in the spec are not part of the description of how to store HTTP messages. A 'payload' can be extracted from WARC records, as a matter of interpretation with regard to the related WARC headers, but no 'payload' is written to WARC records. 

(In the RFC7230 update of HTTP that replaces RFC2616, there is no longer a 'Response' production, but 'HTTP-message' remains, and via 'start-line' variation subsumes both 'Request' and 'Response'. )

**Comment by lljrsr** [comment]
This should fix it. 
Does anyone have a link to a WARC file which contains gzipped bodies? I could not find one and therefore not properly test my code.

**Comment by nlevitt** [comment]
@lljrsr here's one you can use for testing
[WARCPROX-20160211192745816-00000-p74gkeuc.warc.gz](https://github.com/internetarchive/warctools/files/126998/WARCPROX-20160211192745816-00000-p74gkeuc.warc.gz)

**Comment by lljrsr** [comment]
Thanks :) . Everything should work now. Do you like it?

**Comment by lljrsr** [comment]
Are you ready to merge? I will stop working on Friday. It would be nice to merge this into master before that :) .

**Comment by nlevitt** [comment]
I think this line won't work right in python3, should be BytesIO
`GzipFile(fileobj=StringIO(text), mode='rb')`

Having trouble testing though because warcunpack_ia.py is full of code that doesn't work in py3. That sucks, but more importantly, new code should work in py3.

Could you add unit tests to hanzo/httptools/tests/parse_test.py, that would confirm/disconfirm my suspicion, when run on py3?

**Comment by lljrsr** [comment]
You were right.
I changed that and wrote some test which run on python 3 and python 2 now.

**Comment by nlevitt** [comment]
`+    from io import BytesIO as StringIO`

Wha? No need for this confusingness. Python2 has io.BytesIO same as py3.

```
+class PostTestPseudoGzipped(unittest.TestCase):
+    """Tests the parser with a POST request with gzip encoding."""
+    post_request = b"\r\n".join([
+        b"GET / HTTP/1.1",
+        b"Host: example.org",
+        b"",
```

That's not a POST request, it's a GET request. In fact in your test classes, `post_request` isn't used at all. Only the response is used. Best to get rid of that variable. I would shorten the class names to `TestPseudoGzipped` and `TestGzipped`. And change the doc comments to something like "Test parsing of response with content-encoding:gzip declared, but payload not actually gzipped (see https://github.com/internetarchive/warctools/pull/14)" and "Test response with content-encoding:gzip" respectively.

Also I would suggest inlining the gzipped blob. I.e.
```python
        response_list = [
            b"HTTP/1.1 200 OK",
            b"Host: example.org",
            b"Content-Encoding: gzip",
            b"Content-Length: 30",
            b"",
            b"\x1f\x8b\x08\x08G\xb2\xc5V\x00\x03test\x00+I\xad(\xe1\x02\x00'\xda\xec7\x05\x00\x00\x00",
        ]                                                                                
```

**Comment by lljrsr** [comment]
Alright. Yes that was a bit unfortunate :octopus:  . Thanks for the quick reply and good review!

**Comment by nlevitt** [comment]
Thanks!

**Pull request merged**
